### ISSUE TITLE
how to find the prefix url you posted ?  that's amazing

### ISSUE THREAD

**Issue by qianguozheng** [h4ckninja/twitter-video-downloader#1]
Thanks for you sharing.

I analyze the twitter website and see the http request the firefox send, but I how to get the video url , I don't know how to compose it. I think that maybe I need it's developer account of twitter, but during requesting, I found your git.

I want to know how to find this url .
thanks in advance.

**Comment by qianguozheng** [comment]
Looks it doesn't work now.

Request `https://twitter.com/i/videos/tweet/1035056498307522560` got below html. not the actual video m3u8 or real mp4,ts such as.
```
  <!DOCTYPE html>
<html>
<head>
  <style>
    body, html {
      margin: 0;
      padding: 0;
    }

    #video {
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
    }
  </style>
</head>
<body>
  <div id="video"></div>
    <script src="https://abs.twimg.com/web-video-player/TwitterVideoPlayerIframe.9f3fa50c5fbf9f33.js"></script>
</body>
</html>

```

**Comment by qianguozheng** [comment]
Soloved by another rule

**Comment by h4ckninja** [comment]
I've updated the code to account for these changes. :)
