### ISSUE TITLE
`AttributeError: module 'ffmpeg' has no attribute 'input'`

### ISSUE THREAD

**Issue by abetusk** [h4ckninja/twitter-video-downloader#11]
When downloading a video from Twitter, I get the following error:

```
$  ./twitter-dl.py 'https://twitter.com/helenleigh/status/1319420968964624395'
/usr/local/lib/python3.5/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
[+] Multiple resolutions found. Slurping all resolutions.
[+] Downloading 480x270
        [*] Doing the magic ...
Traceback (most recent call last):
  File "./twitter-dl.py", line 225, in <module>
    twitter_dl.download()
  File "./twitter-dl.py", line 106, in download
    ffmpeg\
AttributeError: module 'ffmpeg' has no attribute 'input'
```

My system information:

```
$ python3 --version
Python 3.5.2
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.7 LTS"
```

Note that the line numbers might be different from the main branch as I've tweaked the source (as per issue #7).

I believe I have fixed the issue. From Googling around, I see `ffmpeg-python` has an [issue](https://github.com/kkroening/ffmpeg-python/issues/174) that suggests installing `ffmpeg-python` instaed of `ffmpeg`. Installing `ffmpeg-python` instead of `ffmpeg` resolves the issue for me.

```
pip install ffmpeg-python
```

Note I probably bungled the install as I see `ffmpeg-python` listed in the `requirements.txt`, so this issue should only maybe serve as a reminder to either install `ffmpeg-python` or to make sure a propper install was done of this repo.

**Comment by h4ckninja** [comment]
Thank you so much for the interest and willingness to contribute. I'm just not able to keep up with the ever-changing Twitter and $life and $dayJob have hampered development efforts. [youtube-dl](https://github.com/ytdl-org/youtube-dl) supports Twitter video downloading, so check them out.
