### ISSUE TITLE
This has stopped working

### ISSUE THREAD

**Issue by MonalisaSarewar** [h4ckninja/twitter-video-downloader#13]
player_config_req = self.requests.get(self.video_api + self.tweet_data['id'] + '.json')
get HTTP 404 at the above  line.

Traceback (most recent call last):
  File "twitter-dl.py", line 225, in <module>
    twitter_dl.download()
  File "twitter-dl.py", line 59, in download
    video_host, playlist = self.__get_playlist(token)
  File "twitter-dl.py", line 147, in __get_playlist
    player_config = json.loads(player_config_req.text)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MonalisaSarewar** [comment]
eg : https://twitter.com/GaLe_gale17/status/1320310579278483456
https://twitter.com/TommyGunTyree/status/1320310630402936832

**Comment by ruxtain** [comment]
Instead of a playlist json, I got an html response:


```<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Twitter web player</title>
    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            background: black;
            color: white;
            font-family: "helvetica neue",arial;
            font-size: 14px;
        }

        #message {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translateX(-50%) translateY(-50%);
        }
    </style>
</head>
<body>
  <div id="message">
      The media could not be played.
  </div>
</div>
</body>
</html>
```
seems like Twitter has changed its server logic

**Comment by h4ckninja** [comment]
I see in those two examples, they are retweets of the media. I don't have a good way right now of detecting that. However, I should display a more friendly error message.

If you go to the direct tweet, does it still give you errors?

**Comment by h4ckninja** [comment]
Thank you so much for the interest and willingness to contribute. I'm just not able to keep up with the ever-changing Twitter and $life and $dayJob have hampered development efforts. [youtube-dl](https://github.com/ytdl-org/youtube-dl) supports Twitter video downloading, so check them out.
