### ISSUE TITLE
Create a Pypi package for pip install

### ISSUE THREAD

**Issue by cirosantilli** [h4ckninja/twitter-video-downloader#15]
Thanks for great software.

Here's a simple demo package I maintain for reference on how to do it: https://github.com/cirosantilli/vcdvcd/blob/master/setup.py + release procedure: https://github.com/cirosantilli/vcdvcd#release-procedure it's quite simple. Let me know if any help is needed with this.

I'd also rename executable to just `twitter-dl` and `chmod +x` it as part of release. The sample package above has `vcdcat` as an executable example.

**Comment by h4ckninja** [comment]
Thank you so much for the interest and willingness to contribute. I'm just not able to keep up with the ever-changing Twitter and $life and $dayJob have hampered development efforts. [youtube-dl](https://github.com/ytdl-org/youtube-dl) supports Twitter video downloading, so check them out.
