### ISSUE TITLE
Download Twitter video error.

### ISSUE THREAD

**Issue by qiankunxienb** [h4ckninja/twitter-video-downloader#17]
**Describe the bug**

When I download a video from twitter, it raise an error said:

```python
[+] Multiple resolutions found. Slurping all resolutions.
[+] Downloading 480x270
	[*] Doing the magic ...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcc8808200] trun track id unknown, no tfhd was found
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fbcc8808200] error reading header
output/i/1390791912173424643/480x270.ts: Invalid data found when processing input
```

**To Reproduce**

```bash
twitter-dl.py https://twitter.com/i/status/1390791912173424643
```

**Expected behavior**

download video successful.

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by cirosantilli** [comment]
Reproduce Ubuntu 21.04 ffmpeg 4.3.2 this repo at e02e128dc11572813b487f27439d52ea4768b2b5

```
python3 twitter-dl.py https://mobile.twitter.com/gut5s/status/1389462472646615043
```

or

```
python3 twitter-dl.py https://twitter.com/i/status/1389462472646615043
```

**Comment by cirosantilli** [comment]
OMG `youtube-dl` can download twitter videos: `youtube-dl https://twitter.com/i/status/1389462472646615043`. This project should just be abandoned and all effort merged there.

**Comment by h4ckninja** [comment]
Agreed. I'm just not able to keep up with the ever-changing Twitter and $life and $dayJob have hampered development efforts. Thank you so much for the interest and willingness to contribute.
