### ISSUE TITLE
Rate limit exceed

### ISSUE THREAD

**Issue by alexispe** [h4ckninja/twitter-video-downloader#2]
Hey, I've tested our tool, I have a problem.
This is the output : 
```
alexis@spectre:~/Documents/Projets/my-secret-website/downloader$ python3 twitter-video-downloader.py -v https://twitter.com/RideForLiife/status/773903597725585408
https://twitter.com/RideForLiife/status/773903597725585408
{'errors': [{'message': 'Rate limit exceeded', 'code': 88}]}
Traceback (most recent call last):
  File "twitter-video-downloader.py", line 104, in <module>
    download(args.video_url)
  File "twitter-video-downloader.py", line 47, in download
    m3u8_url_get = m3u8_url_get['track']['playbackUrl']
KeyError: 'track'
```
This line : 
`{'errors': [{'message': 'Rate limit exceeded', 'code': 88}]}`
Is because I've print the m3u8_url_get var.

Can you tell me more about the problem ? 
Ty, Alexis

**Comment by h4ckninja** [comment]
The API does have rate limiting, but I've not run in to that issue and I wasn't able to reproduce it. Are you able to reproduce it again? I'm wondering if the API is trying to tell you that it saw too many connections. I can add a check for that so it exits cleanly.

**Comment by arvindiitm** [comment]
Hi h4ckninja, Thanks for writing this script. I have used this script  and have given a valid video URL but I am getting following  as attached in screenshot . Code is not  able to find the key "Track"
![Screenshot from 2019-03-21 17-28-48](https://user-images.githubusercontent.com/19916120/54750867-29b54500-4bff-11e9-8b5e-a944e914226c.png)

Can you just help me with that

**Comment by tizee** [comment]
> 
> 
> Hi h4ckninja, Thanks for writing this script. I have used this script and have given a valid video URL but I am getting following as attached in screenshot . Code is not able to find the key "Track"
> ![Screenshot from 2019-03-21 17-28-48](https://user-images.githubusercontent.com/19916120/54750867-29b54500-4bff-11e9-8b5e-a944e914226c.png)
> 
> Can you just help me with that

It seems that we could solve this issue by adding 'x-guest-token' in the headers. The 'x-guest-token' was copied from the browser's request headers. 

```python
        headers={
                'authorization': bearer_token,
                # temporary guest token
                'x-guest-token':'1115891533771886594'
                }
        player_config = requests.get('https://api.twitter.com/1.1/videos/tweet/config/' + tweet_id + '.json', headers=headers)

```
When we get the player_config file, the headers's work is done.

But it still bothers me that I need to get x-guest-token when the token is expired.

**Comment by h4ckninja** [comment]
Apologies for the delay, full-time job and all. Thanks @lifedrainfrog for the tip. :) I'll work on this today and try to get a fix pushed.

**Comment by h4ckninja** [comment]
The fix is going to take a bit longer. I see what's going on (Twitter keeps changing things ... :P), but as a temporary work-around, it _seems_ that you can open the tweet in question in your browser first, then download it.

**Comment by h4ckninja** [comment]
See commit https://github.com/h4ckninja/twitter-video-downloader/commit/9b3954f61a5520c55238e51939fe0792d566547c. I incorrectly tagged #1 but meant to tag this one. :P 

Short of it: Still working on it, but this rewrite makes my life a lot easier. And I've added a graceful exit. Apologies for the delay, $life happened.

**Comment by devkarim** [comment]
@h4ckninja any hope on this? I ran against the same issue, dunno what exactly is causing this kind of restriction to happen even though I used it only once 😄

**Comment by h4ckninja** [comment]
Yes, I'm working on this today. For now, if you try again say 30 minutes later, it seems to work. I _think_ Twitter is giving the public API key that I'm using a limited number of uses, and once anonymous users use it up, that's it. But if you wait a bit, it seems to reset and it works for a while again. But I'm going to try to find a way to address that.

**Comment by devkarim** [comment]
I've figured it out, you have to get a guest token by doing a POST request to https://api.twitter.com/1.1/guest/activate.json and then add the guest token in 'x-guest-token' header. Here you go a demo of it that I'm currently using;

```python
def __get_guest_token(self):
        res = self.s.post("https://api.twitter.com/1.1/guest/activate.json")
        res_json = json.loads(res.text)
        self.s.headers.update({'x-guest-token': res_json.get('guest_token')})
```

Good work though, the video downloader works pretty well! 😅
