### ISSUE TITLE
Single resolution not implemented

### ISSUE THREAD

**Issue by belisards** [h4ckninja/twitter-video-downloader#6]
Hi, thanks for your script. I'm using to download several videos at once, but some give me this error:

[Debug] [Tweet URL] https://twitter.com/ThiagoTisca/status/1158118513682395136
[Debug] [Video Player Body] 
[Debug] [JS File Body] 
[Debug] [Bearer Token] Bearer AAAAAAAAAAAAAAAAAAAAAIK1zgAAAAAA2tUWuhGZ2JceoId5GwYWU5GspY4%3DUq7gzFoCZs1QfwGoVdvSac3IniczZEYXIcDyumCauIXpcAPorE
[Debug] [Player Config JSON] 
[Debug] [M3U8 Response] 
[-] Sorry, single resolution video download is not yet implemented. Please submit a bug report with the link to the tweet.
[Debug] [Tweet URL] https://twitter.com/Mattheuss827/status/1157788625406500866
[Debug] [Video Player Body] 
[Debug] [JS File Body] 
[Debug] [Bearer Token] Bearer AAAAAAAAAAAAAAAAAAAAAIK1zgAAAAAA2tUWuhGZ2JceoId5GwYWU5GspY4%3DUq7gzFoCZs1QfwGoVdvSac3IniczZEYXIcDyumCauIXpcAPorE
[Debug] [Player Config JSON] 
[Debug] [M3U8 Response] 
[-] Sorry, single resolution video download is not yet implemented. Please submit a bug report with the link to the tweet.

I would like to check if every occurrence of this error is due the fact the tweets actually contains GIFs.

**Comment by satish2832** [comment]
Latest update, here is providing twitter video download mp3 and thumbnail API https://mp3downy.com/twitter-video-downloader-api

**Comment by h4ckninja** [comment]
#8 should address this. :)
