### ISSUE TITLE
Python 3.5.2 @ TypeError: invalid file: PosixPath

### ISSUE THREAD

**Issue by webolizzer** [h4ckninja/twitter-video-downloader#7]
I get following error message in Python 3.5.2 when i am trying to download a video:

$ python3 twitter-dl.py -d https://twitter.com/klara_sjo/status/1205228036225949696?s=20
[Debug] [Tweet URL] https://twitter.com/klara_sjo/status/1205228036225949696
[Debug] [Video Player Body] 
[Debug] [JS File Body] 
[Debug] [Bearer Token] Bearer AAAAAAAAAAAAAAAAAAAAAIK1zgAAAAAA2tUWuhGZ2JceoId5GwYWU5GspY4%3DUq7gzFoCZs1QfwGoVdvSac3IniczZEYXIcDyumCauIXpcAPorE
[Debug] [Player Config JSON] 
[Debug] [M3U8 Response] 
[+] Multiple resolutions found. Slurping all resolutions.
[+] Downloading 320x320
Traceback (most recent call last):
  File "twitter-dl.py", line 200, in <module>
    twitter_dl.download()
  File "twitter-dl.py", line 94, in download
    with open(f, 'rb') as fd:
TypeError: invalid file: PosixPath('output/klara_sjo/1205228036225949696/xgSZf0Zyxmgc1zI0.ts')

**Comment by satish2832** [comment]
Latest update, here is providing twitter video download mp3 and thumbnail API https://mp3downy.com/twitter-video-downloader-api

**Comment by h4ckninja** [comment]
I haven't been able to reproduce this. Is this still happening?

**Comment by abetusk** [comment]
I just got this error. Looking around, I see this [SO](https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t) about it that suggests wrapping the result in a `str` cast.

I did what was suggested and I'm not getting this error anymore (though now I'm running into another error). Here's a diff:

```
@@ -96,7 +96,8 @@ class TwitterDownloader:
                                # Shamelessly taken from https://stackoverflow.com/questions/13613336/python-concatenate-text-files/27077437#27077437
                                with open(str(ts_full_file), 'wb') as wfd:
                                        for f in ts_list:
-                                               with open(f, 'rb') as fd:
+                                               #with open(f, 'rb') as fd:
+                                               with open(str(f), 'rb') as fd:
                                                        shutil.copyfileobj(fd, wfd, 1024 * 1024 * 10)
  ```

Here's some more information:

```
$ python3 --version
Python 3.5.2
```

**Comment by h4ckninja** [comment]
Thank you so much for the interest and willingness to contribute. I'm just not able to keep up with the ever-changing Twitter and $life and $dayJob have hampered development efforts. [youtube-dl](https://github.com/ytdl-org/youtube-dl) supports Twitter video downloading, so check them out.
