### ISSUE TITLE
video downlaod error

### ISSUE THREAD

**Issue by iceking112** [h4ckninja/twitter-video-downloader#9]
when download a video it's not always success, offen show this erorr:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='abs.twimg.com', port=443): Max retries exceeded with url: /web-video-player/TwitterVideoPlayerIframe.cefd459559024bfb.js (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

**Comment by anushkmittal** [comment]
@iceking112 were you able to get it to work?

**Comment by h4ckninja** [comment]
I haven't reproduced this. Is it still an issue?

**Comment by h4ckninja** [comment]
Thank you so much for the interest and willingness to contribute. I'm just not able to keep up with the ever-changing Twitter and $life and $dayJob have hampered development efforts. [youtube-dl](https://github.com/ytdl-org/youtube-dl) supports Twitter video downloading, so check them out.
